### ISSUE TITLE
Error after import library

### ISSUE THREAD

**Issue by tifa2100** [cmglez10/ng-datatable#13]
I face below error after add "angular-8-datatable"

`ERROR in ./node_modules/angular-8-datatable/src/app/datapaginator-component/bootstrapdatapaginator.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: .../node_modules/angular-8-datatable/src/app/datapaginator-component/bootstrapdatapaginator.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at .../node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR in ./node_modules/angular-8-datatable/src/app/datapaginator-component/datapaginator.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: .../node_modules/angular-8-datatable/src/app/datapaginator-component/datapaginator.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at .../node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR in ./node_modules/angular-8-datatable/src/app/datasorter-component/datasorter.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: .../node_modules/angular-8-datatable/src/app/datasorter-component/datasorter.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at .../node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR in ./node_modules/angular-8-datatable/src/app/services/datatable.service.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: .../node_modules/angular-8-datatable/src/app/services/datatable.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at .../node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR in ./node_modules/angular-8-datatable/src/datatable.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: .../node_modules/angular-8-datatable/src/datatable.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at .../node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

it seems I am missing install a library but I don't know which one 

my package.json file like below

`"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@auth0/angular-jwt": "^3.0.1",
    "angular-8-datatable": "^1.0.2",
    "bootstrap": "^4.4.1",
    "core-js": "^3.6.1",
    "jquery": "^3.4.1",
    "ngx-toastr": "^11.2.1",
    "popper.js": "^1.16.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },`

could you please help me solving this issue ?

**Comment by PascalHonegger** [comment]
If you're still having issues and want to use a table library like this one I can recommend my fork (https://github.com/PascalHonegger/ng-datatable) which has a new build pipeline with Angular 9 and ivy support.
